# Generated by Django 5.0 on 2023-12-29 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
